version: '3.9'

services:
  ruby:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    environment:
      - THREAD_POOL=0:16
      - WEB_CONCURRENCY=8
    working_dir: /app
    command: rackup
    ports: 
      - 4000:4000
volumes:
  rubygems:
